name: "flutter_develop_template"
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  cached_network_image: ^3.4.1
  curved_labeled_navigation_bar: ^2.0.6
  dio: ^5.8.0+1
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  go_router: ^14.8.1
  permission_handler: ^11.4.0
  provider: ^6.1.2
  spring: ^2.0.2
  tdesign_flutter: ^0.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
